export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const CONTACTS_REQUEST_SUCCES = 'CONTACTS_REQUEST_SUCCES';
export const SHOW_CONTACT_INFO = 'SHOW_CONTACT_INFO';